name: Validacion Automatizada de Sintaxis

# El pipeline se activará cada vez que hagas un 'push' a la rama principal
on:
  push:
    branches: [ main, master ]

jobs:
  control-calidad:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el código dentro de la máquina virtual de GitHub
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    # Paso 2: Configurar el entorno de Python en la máquina virtual
    - name: Configurar entorno Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Paso 3: Verificar la sintaxis del script de Python
    - name: Comprobar sintaxis de mi_script.py
      run: |
        echo "=== Comprobando Python ==="
        python -m py_compile mi_script.py

    # Paso 4: Instalar una herramienta para validar el YAML y ejecutarla
    - name: Comprobar sintaxis de config.yaml
      run: |
        echo "=== Comprobando YAML ==="
        pip install yamllint
        yamllint config.yaml
